package types

import (
	"fmt"
	"go/ast"
	goParser "go/parser"
	goToken "go/token"
	"go/types"

	"github.com/elk-language/elk/env"
	"golang.org/x/tools/go/packages"
)

type GoPackageImporter struct {
	m map[string]*packages.Package
}

func NewGoPackageImporter() *GoPackageImporter {
	return &GoPackageImporter{
		m: make(map[string]*packages.Package),
	}
}

func NewGoPackageImporterFromSlice(pkgs []*packages.Package) *GoPackageImporter {
	m := NewGoPackageImporter()

	for _, pkg := range pkgs {
		m.m[pkg.String()] = pkg
	}

	return m
}

func NewGoPackageImporterForDir(dir string) (*GoPackageImporter, error) {
	packagesCfg := &packages.Config{
		Mode: packages.NeedTypes |
			packages.NeedTypesSizes |
			packages.NeedImports |
			packages.NeedDeps,
		Dir: dir,
	}
	pkgs, err := packages.Load(packagesCfg, "./...")
	if err != nil {
		return nil, fmt.Errorf("go package importer error: %w", err)
	}

	return NewGoPackageImporterFromSlice(pkgs), nil
}

func MustNewGoPackageImporterForDir(dir string) *GoPackageImporter {
	imp, err := NewGoPackageImporterForDir(dir)
	if err != nil {
		panic(err)
	}
	return imp
}

func NewGoPackageImporterForElk() (*GoPackageImporter, error) {
	return NewGoPackageImporterForDir(env.ELKPATH)
}

func MustNewGoPackageImporterForElk() *GoPackageImporter {
	imp, err := NewGoPackageImporterForElk()
	if err != nil {
		panic(err)
	}
	return imp
}

func (p *GoPackageImporter) Import(path string) (*types.Package, error) {
	pkg, ok := p.m[path]
	if !ok {
		return nil, fmt.Errorf("invalid import: %s", path)
	}
	return pkg.Types, nil
}

// GoTypechecker typechecks Go source code generated by the Elk to Go compiler.
type GoTypechecker struct {
	cfg *types.Config
}

func NewGoTypechecker() (*GoTypechecker, error) {
	return NewGoTypecheckerForDir(env.ELKPATH)
}

func NewGoTypecheckerForDir(dir string) (*GoTypechecker, error) {
	importer, err := NewGoPackageImporterForDir(dir)
	if err != nil {
		return nil, err
	}

	return &GoTypechecker{
		cfg: &types.Config{
			Importer: importer,
		},
	}, nil
}

func NewGoTypecheckerWithImporter(importer *GoPackageImporter) *GoTypechecker {
	return &GoTypechecker{
		cfg: &types.Config{
			Importer: importer,
		},
	}
}

// CheckString checks the given go source code
func (t *GoTypechecker) CheckString(source string) error {
	fset := goToken.NewFileSet()
	file, err := goParser.ParseFile(fset, "<repl>", source, goParser.AllErrors)
	if err != nil {
		return fmt.Errorf("go parse error: %w", err)
	}

	_, err = t.cfg.Check("<repl>", fset, []*ast.File{file}, nil)
	if err != nil {
		return fmt.Errorf("go typecheck error: %w", err)
	}

	return nil
}

// CheckString checks the given go source code
func (t *GoTypechecker) CheckBytes(source []byte) error {
	fset := goToken.NewFileSet()
	file, err := goParser.ParseFile(fset, "<repl>", source, goParser.AllErrors)
	if err != nil {
		return fmt.Errorf("go parse error: %w", err)
	}

	_, err = t.cfg.Check("<repl>", fset, []*ast.File{file}, nil)
	if err != nil {
		return fmt.Errorf("go typecheck error: %w", err)
	}

	return nil
}
