package vm

import "github.com/elk-language/elk/value"

func InitGlobalEnvironment() {
	value.InitGlobalEnvironment()

	initIterator()
	initArrayList()
	initArrayListIterator()
	initArrayTuple()
	initArrayTupleIterator()
	initBeginlessClosedRange()
	initBeginlessOpenRange()
	initBigFloat()
	initChar()
	initClass()
	initMixin()
	initModule()
	initInterface()
	initClosedRange()
	initClosedRangeIterator()
	initComparable()
	initEndlessClosedRange()
	initEndlessClosedRangeIterator()
	initEndlessOpenRange()
	initEndlessOpenRangeIterator()
	initNil()
	initFloat()
	initHashMap()
	initHashMapIterator()
	initHashRecord()
	initHashRecordIterator()
	initHashSet()
	initHashSetIterator()
	initInt()
	initIntIterator()
	initKernel()
	initDebug()
	initLeftOpenRange()
	initLeftOpenRangeIterator()
	initMethod()
	initMixin()
	initModule()
	initOpenRange()
	initOpenRangeIterator()
	initPair()
	initRegex()
	initRightOpenRange()
	initRightOpenRangeIterator()
	initString()
	initStringCharIterator()
	initStringByteIterator()
	initStringGraphemeIterator()
	initSymbol()
	initDuration()
	initTimezone()
	initTime()
	initValue()
	initGenerator()
	initThread()
	initThreadPool()
	initChannel()
	initWaitGroup()
	initMutex()
	initRWMutex()
	initROMutex()
	initOnce()
	initStackTrace()
	initStackTraceIterator()
	initCallFrame()
	initPromise()
	initPosition()
	initSpan()
	initToken()
	initLocation()
	initPath()
}

func init() {
	InitGlobalEnvironment()
}
