package lexer

import "testing"

func TestCollectionLiteral(t *testing.T) {
	tests := testTable{
		"incorrect word delimiters": {
			input: "%w<foo bar   baz>",
			want: []*Token{
				{
					TokenType:  ErrorToken,
					Value:      "invalid word collection literal delimiters `%%w`",
					StartByte:  0,
					ByteLength: 2,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  LessToken,
					StartByte:  2,
					ByteLength: 1,
					Line:       1,
					Column:     3,
				},
				{
					TokenType:  IdentifierToken,
					Value:      "foo",
					StartByte:  3,
					ByteLength: 3,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  IdentifierToken,
					Value:      "bar",
					StartByte:  7,
					ByteLength: 3,
					Line:       1,
					Column:     8,
				},
				{
					TokenType:  IdentifierToken,
					Value:      "baz",
					StartByte:  13,
					ByteLength: 3,
					Line:       1,
					Column:     14,
				},
				{
					TokenType:  GreaterToken,
					StartByte:  16,
					ByteLength: 1,
					Line:       1,
					Column:     17,
				},
			},
		},
		"incorrect symbol delimiters": {
			input: "%s<foo bar   baz>",
			want: []*Token{
				{
					TokenType:  ErrorToken,
					Value:      "invalid symbol collection literal delimiters `%%s`",
					StartByte:  0,
					ByteLength: 2,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  LessToken,
					StartByte:  2,
					ByteLength: 1,
					Line:       1,
					Column:     3,
				},
				{
					TokenType:  IdentifierToken,
					Value:      "foo",
					StartByte:  3,
					ByteLength: 3,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  IdentifierToken,
					Value:      "bar",
					StartByte:  7,
					ByteLength: 3,
					Line:       1,
					Column:     8,
				},
				{
					TokenType:  IdentifierToken,
					Value:      "baz",
					StartByte:  13,
					ByteLength: 3,
					Line:       1,
					Column:     14,
				},
				{
					TokenType:  GreaterToken,
					StartByte:  16,
					ByteLength: 1,
					Line:       1,
					Column:     17,
				},
			},
		},
		"incorrect hex delimiters": {
			input: "%x<45a 101   fff>",
			want: []*Token{
				{
					TokenType:  ErrorToken,
					Value:      "invalid hex collection literal delimiters `%%x`",
					StartByte:  0,
					ByteLength: 2,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  LessToken,
					StartByte:  2,
					ByteLength: 1,
					Line:       1,
					Column:     3,
				},
				{
					TokenType:  DecIntToken,
					Value:      "45",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  IdentifierToken,
					Value:      "a",
					StartByte:  5,
					ByteLength: 1,
					Line:       1,
					Column:     6,
				},
				{
					TokenType:  DecIntToken,
					Value:      "101",
					StartByte:  7,
					ByteLength: 3,
					Line:       1,
					Column:     8,
				},
				{
					TokenType:  IdentifierToken,
					Value:      "fff",
					StartByte:  13,
					ByteLength: 3,
					Line:       1,
					Column:     14,
				},
				{
					TokenType:  GreaterToken,
					StartByte:  16,
					ByteLength: 1,
					Line:       1,
					Column:     17,
				},
			},
		},
		"incorrect binary delimiters": {
			input: "%b<110 101   111>",
			want: []*Token{
				{
					TokenType:  ErrorToken,
					Value:      "invalid binary collection literal delimiters `%%b`",
					StartByte:  0,
					ByteLength: 2,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  LessToken,
					StartByte:  2,
					ByteLength: 1,
					Line:       1,
					Column:     3,
				},
				{
					TokenType:  DecIntToken,
					Value:      "110",
					StartByte:  3,
					ByteLength: 3,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  DecIntToken,
					Value:      "101",
					StartByte:  7,
					ByteLength: 3,
					Line:       1,
					Column:     8,
				},
				{
					TokenType:  DecIntToken,
					Value:      "111",
					StartByte:  13,
					ByteLength: 3,
					Line:       1,
					Column:     14,
				},
				{
					TokenType:  GreaterToken,
					StartByte:  16,
					ByteLength: 1,
					Line:       1,
					Column:     17,
				},
			},
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			tokenTest(tc, t)
		})
	}
}

func TestArray(t *testing.T) {
	tests := testTable{
		"regular array": {
			input: "[1, 2, 3.0, 'foo', :bar]",
			want: []*Token{
				{
					TokenType:  LBracketToken,
					StartByte:  0,
					ByteLength: 1,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  DecIntToken,
					Value:      "1",
					StartByte:  1,
					ByteLength: 1,
					Line:       1,
					Column:     2,
				},
				{
					TokenType:  CommaToken,
					StartByte:  2,
					ByteLength: 1,
					Line:       1,
					Column:     3,
				},
				{
					TokenType:  DecIntToken,
					Value:      "2",
					StartByte:  4,
					ByteLength: 1,
					Line:       1,
					Column:     5,
				},
				{
					TokenType:  CommaToken,
					StartByte:  5,
					ByteLength: 1,
					Line:       1,
					Column:     6,
				},
				{
					TokenType:  FloatToken,
					Value:      "3.0",
					StartByte:  7,
					ByteLength: 3,
					Line:       1,
					Column:     8,
				},
				{
					TokenType:  CommaToken,
					StartByte:  10,
					ByteLength: 1,
					Line:       1,
					Column:     11,
				},
				{
					TokenType:  RawStringToken,
					Value:      "foo",
					StartByte:  12,
					ByteLength: 5,
					Line:       1,
					Column:     13,
				},
				{
					TokenType:  CommaToken,
					StartByte:  17,
					ByteLength: 1,
					Line:       1,
					Column:     18,
				},
				{
					TokenType:  SymbolBegToken,
					StartByte:  19,
					ByteLength: 1,
					Line:       1,
					Column:     20,
				},
				{
					TokenType:  IdentifierToken,
					Value:      "bar",
					StartByte:  20,
					ByteLength: 3,
					Line:       1,
					Column:     21,
				},
				{
					TokenType:  RBracketToken,
					StartByte:  23,
					ByteLength: 1,
					Line:       1,
					Column:     24,
				},
			},
		},
		"word array": {
			input: `%w[
foo bar  
baz]`,
			want: []*Token{
				{
					TokenType:  WordArrayBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  RawStringToken,
					Value:      "foo",
					StartByte:  4,
					ByteLength: 3,
					Line:       2,
					Column:     1,
				},
				{
					TokenType:  RawStringToken,
					Value:      "bar",
					StartByte:  8,
					ByteLength: 3,
					Line:       2,
					Column:     5,
				},
				{
					TokenType:  RawStringToken,
					Value:      "baz",
					StartByte:  14,
					ByteLength: 3,
					Line:       3,
					Column:     1,
				},
				{
					TokenType:  WordArrayEndToken,
					StartByte:  17,
					ByteLength: 1,
					Line:       3,
					Column:     4,
				},
			},
		},
		"symbol array": {
			input: "%s[foo bar   baz]",
			want: []*Token{
				{
					TokenType:  SymbolArrayBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  RawStringToken,
					Value:      "foo",
					StartByte:  3,
					ByteLength: 3,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  RawStringToken,
					Value:      "bar",
					StartByte:  7,
					ByteLength: 3,
					Line:       1,
					Column:     8,
				},
				{
					TokenType:  RawStringToken,
					Value:      "baz",
					StartByte:  13,
					ByteLength: 3,
					Line:       1,
					Column:     14,
				},
				{
					TokenType:  SymbolArrayEndToken,
					StartByte:  16,
					ByteLength: 1,
					Line:       1,
					Column:     17,
				},
			},
		},
		"hex array": {
			input: "%x[ff 4_e   234]",
			want: []*Token{
				{
					TokenType:  HexArrayBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  HexIntToken,
					Value:      "ff",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  HexIntToken,
					Value:      "4e",
					StartByte:  6,
					ByteLength: 3,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  HexIntToken,
					Value:      "234",
					StartByte:  12,
					ByteLength: 3,
					Line:       1,
					Column:     13,
				},
				{
					TokenType:  HexArrayEndToken,
					StartByte:  15,
					ByteLength: 1,
					Line:       1,
					Column:     16,
				},
			},
		},
		"hex array with invalid content": {
			input: "%x[ff 4ghij   234]",
			want: []*Token{
				{
					TokenType:  HexArrayBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  HexIntToken,
					Value:      "ff",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  ErrorToken,
					Value:      "invalid int literal",
					StartByte:  6,
					ByteLength: 5,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  HexIntToken,
					Value:      "234",
					StartByte:  14,
					ByteLength: 3,
					Line:       1,
					Column:     15,
				},
				{
					TokenType:  HexArrayEndToken,
					StartByte:  17,
					ByteLength: 1,
					Line:       1,
					Column:     18,
				},
			},
		},
		"binary array": {
			input: "%b[11 1_0   101]",
			want: []*Token{
				{
					TokenType:  BinArrayBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  BinIntToken,
					Value:      "11",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  BinIntToken,
					Value:      "10",
					StartByte:  6,
					ByteLength: 3,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  BinIntToken,
					Value:      "101",
					StartByte:  12,
					ByteLength: 3,
					Line:       1,
					Column:     13,
				},
				{
					TokenType:  BinArrayEndToken,
					StartByte:  15,
					ByteLength: 1,
					Line:       1,
					Column:     16,
				},
			},
		},
		"binary array with invalid content": {
			input: "%b[11 1ghij   101]",
			want: []*Token{
				{
					TokenType:  BinArrayBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  BinIntToken,
					Value:      "11",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  ErrorToken,
					Value:      "invalid int literal",
					StartByte:  6,
					ByteLength: 5,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  BinIntToken,
					Value:      "101",
					StartByte:  14,
					ByteLength: 3,
					Line:       1,
					Column:     15,
				},
				{
					TokenType:  BinArrayEndToken,
					StartByte:  17,
					ByteLength: 1,
					Line:       1,
					Column:     18,
				},
			},
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			tokenTest(tc, t)
		})
	}
}

func TestSet(t *testing.T) {
	tests := testTable{
		"regular set": {
			input: "%{1, 2, 3.0, 'foo', :bar}",
			want: []*Token{
				{
					TokenType:  SetLiteralBegToken,
					StartByte:  0,
					ByteLength: 2,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  DecIntToken,
					Value:      "1",
					StartByte:  2,
					ByteLength: 1,
					Line:       1,
					Column:     3,
				},
				{
					TokenType:  CommaToken,
					StartByte:  3,
					ByteLength: 1,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  DecIntToken,
					Value:      "2",
					StartByte:  5,
					ByteLength: 1,
					Line:       1,
					Column:     6,
				},
				{
					TokenType:  CommaToken,
					StartByte:  6,
					ByteLength: 1,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  FloatToken,
					Value:      "3.0",
					StartByte:  8,
					ByteLength: 3,
					Line:       1,
					Column:     9,
				},
				{
					TokenType:  CommaToken,
					StartByte:  11,
					ByteLength: 1,
					Line:       1,
					Column:     12,
				},
				{
					TokenType:  RawStringToken,
					Value:      "foo",
					StartByte:  13,
					ByteLength: 5,
					Line:       1,
					Column:     14,
				},
				{
					TokenType:  CommaToken,
					StartByte:  18,
					ByteLength: 1,
					Line:       1,
					Column:     19,
				},
				{
					TokenType:  SymbolBegToken,
					StartByte:  20,
					ByteLength: 1,
					Line:       1,
					Column:     21,
				},
				{
					TokenType:  IdentifierToken,
					Value:      "bar",
					StartByte:  21,
					ByteLength: 3,
					Line:       1,
					Column:     22,
				},
				{
					TokenType:  RBraceToken,
					StartByte:  24,
					ByteLength: 1,
					Line:       1,
					Column:     25,
				},
			},
		},
		"word set": {
			input: "%w{foo bar   baz}",
			want: []*Token{
				{
					TokenType:  WordSetBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  RawStringToken,
					Value:      "foo",
					StartByte:  3,
					ByteLength: 3,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  RawStringToken,
					Value:      "bar",
					StartByte:  7,
					ByteLength: 3,
					Line:       1,
					Column:     8,
				},
				{
					TokenType:  RawStringToken,
					Value:      "baz",
					StartByte:  13,
					ByteLength: 3,
					Line:       1,
					Column:     14,
				},
				{
					TokenType:  WordSetEndToken,
					StartByte:  16,
					ByteLength: 1,
					Line:       1,
					Column:     17,
				},
			},
		},
		"symbol set": {
			input: "%s{foo bar   baz}",
			want: []*Token{
				{
					TokenType:  SymbolSetBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  RawStringToken,
					Value:      "foo",
					StartByte:  3,
					ByteLength: 3,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  RawStringToken,
					Value:      "bar",
					StartByte:  7,
					ByteLength: 3,
					Line:       1,
					Column:     8,
				},
				{
					TokenType:  RawStringToken,
					Value:      "baz",
					StartByte:  13,
					ByteLength: 3,
					Line:       1,
					Column:     14,
				},
				{
					TokenType:  SymbolSetEndToken,
					StartByte:  16,
					ByteLength: 1,
					Line:       1,
					Column:     17,
				},
			},
		},
		"hex set": {
			input: "%x{ff 4_e   234}",
			want: []*Token{
				{
					TokenType:  HexSetBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  HexIntToken,
					Value:      "ff",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  HexIntToken,
					Value:      "4e",
					StartByte:  6,
					ByteLength: 3,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  HexIntToken,
					Value:      "234",
					StartByte:  12,
					ByteLength: 3,
					Line:       1,
					Column:     13,
				},
				{
					TokenType:  HexSetEndToken,
					StartByte:  15,
					ByteLength: 1,
					Line:       1,
					Column:     16,
				},
			},
		},
		"hex set with invalid content": {
			input: "%x{ff 4ghij   234}",
			want: []*Token{
				{
					TokenType:  HexSetBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  HexIntToken,
					Value:      "ff",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  ErrorToken,
					Value:      "invalid int literal",
					StartByte:  6,
					ByteLength: 5,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  HexIntToken,
					Value:      "234",
					StartByte:  14,
					ByteLength: 3,
					Line:       1,
					Column:     15,
				},
				{
					TokenType:  HexSetEndToken,
					StartByte:  17,
					ByteLength: 1,
					Line:       1,
					Column:     18,
				},
			},
		},
		"binary array": {
			input: "%b[11 1_0   101]",
			want: []*Token{
				{
					TokenType:  BinArrayBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  BinIntToken,
					Value:      "11",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  BinIntToken,
					Value:      "10",
					StartByte:  6,
					ByteLength: 3,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  BinIntToken,
					Value:      "101",
					StartByte:  12,
					ByteLength: 3,
					Line:       1,
					Column:     13,
				},
				{
					TokenType:  BinArrayEndToken,
					StartByte:  15,
					ByteLength: 1,
					Line:       1,
					Column:     16,
				},
			},
		},
		"binary set with invalid content": {
			input: "%b{11 1ghij   101}",
			want: []*Token{
				{
					TokenType:  BinSetBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  BinIntToken,
					Value:      "11",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  ErrorToken,
					Value:      "invalid int literal",
					StartByte:  6,
					ByteLength: 5,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  BinIntToken,
					Value:      "101",
					StartByte:  14,
					ByteLength: 3,
					Line:       1,
					Column:     15,
				},
				{
					TokenType:  BinSetEndToken,
					StartByte:  17,
					ByteLength: 1,
					Line:       1,
					Column:     18,
				},
			},
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			tokenTest(tc, t)
		})
	}
}

func TestTuple(t *testing.T) {
	tests := testTable{
		"regular tuple": {
			input: "%(1, 2, 3.0, 'foo', :bar)",
			want: []*Token{
				{
					TokenType:  TupleLiteralBegToken,
					StartByte:  0,
					ByteLength: 2,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  DecIntToken,
					Value:      "1",
					StartByte:  2,
					ByteLength: 1,
					Line:       1,
					Column:     3,
				},
				{
					TokenType:  CommaToken,
					StartByte:  3,
					ByteLength: 1,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  DecIntToken,
					Value:      "2",
					StartByte:  5,
					ByteLength: 1,
					Line:       1,
					Column:     6,
				},
				{
					TokenType:  CommaToken,
					StartByte:  6,
					ByteLength: 1,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  FloatToken,
					Value:      "3.0",
					StartByte:  8,
					ByteLength: 3,
					Line:       1,
					Column:     9,
				},
				{
					TokenType:  CommaToken,
					StartByte:  11,
					ByteLength: 1,
					Line:       1,
					Column:     12,
				},
				{
					TokenType:  RawStringToken,
					Value:      "foo",
					StartByte:  13,
					ByteLength: 5,
					Line:       1,
					Column:     14,
				},
				{
					TokenType:  CommaToken,
					StartByte:  18,
					ByteLength: 1,
					Line:       1,
					Column:     19,
				},
				{
					TokenType:  SymbolBegToken,
					StartByte:  20,
					ByteLength: 1,
					Line:       1,
					Column:     21,
				},
				{
					TokenType:  IdentifierToken,
					Value:      "bar",
					StartByte:  21,
					ByteLength: 3,
					Line:       1,
					Column:     22,
				},
				{
					TokenType:  RParenToken,
					StartByte:  24,
					ByteLength: 1,
					Line:       1,
					Column:     25,
				},
			},
		},
		"word tuple": {
			input: "%w(foo bar   baz)",
			want: []*Token{
				{
					TokenType:  WordTupleBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  RawStringToken,
					Value:      "foo",
					StartByte:  3,
					ByteLength: 3,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  RawStringToken,
					Value:      "bar",
					StartByte:  7,
					ByteLength: 3,
					Line:       1,
					Column:     8,
				},
				{
					TokenType:  RawStringToken,
					Value:      "baz",
					StartByte:  13,
					ByteLength: 3,
					Line:       1,
					Column:     14,
				},
				{
					TokenType:  WordTupleEndToken,
					StartByte:  16,
					ByteLength: 1,
					Line:       1,
					Column:     17,
				},
			},
		},
		"symbol tuple": {
			input: "%s(foo bar   baz)",
			want: []*Token{
				{
					TokenType:  SymbolTupleBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  RawStringToken,
					Value:      "foo",
					StartByte:  3,
					ByteLength: 3,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  RawStringToken,
					Value:      "bar",
					StartByte:  7,
					ByteLength: 3,
					Line:       1,
					Column:     8,
				},
				{
					TokenType:  RawStringToken,
					Value:      "baz",
					StartByte:  13,
					ByteLength: 3,
					Line:       1,
					Column:     14,
				},
				{
					TokenType:  SymbolTupleEndToken,
					StartByte:  16,
					ByteLength: 1,
					Line:       1,
					Column:     17,
				},
			},
		},
		"hex tuple": {
			input: "%x(ff 4_e   234)",
			want: []*Token{
				{
					TokenType:  HexTupleBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  HexIntToken,
					Value:      "ff",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  HexIntToken,
					Value:      "4e",
					StartByte:  6,
					ByteLength: 3,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  HexIntToken,
					Value:      "234",
					StartByte:  12,
					ByteLength: 3,
					Line:       1,
					Column:     13,
				},
				{
					TokenType:  HexTupleEndToken,
					StartByte:  15,
					ByteLength: 1,
					Line:       1,
					Column:     16,
				},
			},
		},
		"hex tuple with invalid content": {
			input: "%x(ff 4ghij   234)",
			want: []*Token{
				{
					TokenType:  HexTupleBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  HexIntToken,
					Value:      "ff",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  ErrorToken,
					Value:      "invalid int literal",
					StartByte:  6,
					ByteLength: 5,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  HexIntToken,
					Value:      "234",
					StartByte:  14,
					ByteLength: 3,
					Line:       1,
					Column:     15,
				},
				{
					TokenType:  HexTupleEndToken,
					StartByte:  17,
					ByteLength: 1,
					Line:       1,
					Column:     18,
				},
			},
		},
		"binary tuple": {
			input: "%b(11 1_0   101)",
			want: []*Token{
				{
					TokenType:  BinTupleBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  BinIntToken,
					Value:      "11",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  BinIntToken,
					Value:      "10",
					StartByte:  6,
					ByteLength: 3,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  BinIntToken,
					Value:      "101",
					StartByte:  12,
					ByteLength: 3,
					Line:       1,
					Column:     13,
				},
				{
					TokenType:  BinTupleEndToken,
					StartByte:  15,
					ByteLength: 1,
					Line:       1,
					Column:     16,
				},
			},
		},
		"binary tuple with invalid content": {
			input: "%b(11 1ghij   101)",
			want: []*Token{
				{
					TokenType:  BinTupleBegToken,
					StartByte:  0,
					ByteLength: 3,
					Line:       1,
					Column:     1,
				},
				{
					TokenType:  BinIntToken,
					Value:      "11",
					StartByte:  3,
					ByteLength: 2,
					Line:       1,
					Column:     4,
				},
				{
					TokenType:  ErrorToken,
					Value:      "invalid int literal",
					StartByte:  6,
					ByteLength: 5,
					Line:       1,
					Column:     7,
				},
				{
					TokenType:  BinIntToken,
					Value:      "101",
					StartByte:  14,
					ByteLength: 3,
					Line:       1,
					Column:     15,
				},
				{
					TokenType:  BinTupleEndToken,
					StartByte:  17,
					ByteLength: 1,
					Line:       1,
					Column:     18,
				},
			},
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			tokenTest(tc, t)
		})
	}
}
